### EY Datascience Challenge ###
**Import relevant libraries and datasets**

divide the test data into dataset for prediction and dataset for evaluation

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import normalize
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import to_categorical

Using TensorFlow backend.

In [2]:
#Reading training data
df = pd.read_csv ("data_train.csv")
df = df.loc[:,'hash':'y_exit']
df.fillna('',inplace=True)

In [3]:
#Reading test data
df_test = pd.read_csv ("data_test.csv")
df_test = df_test.loc[:,'hash':'y_exit']
df_test.fillna('',inplace=True)

In [4]:
#divide the test data into pred and eval
df_test['time_entry']=pd.to_timedelta(df_test['time_entry'])
df_test['time_exit']=pd.to_timedelta(df_test['time_exit'])

df_test_pred = df_test[df_test['x_exit'] == ""]
df_test_eval = df_test[df_test['x_exit'] != ""]

**First Look at the Data**

Type and informations of the datasets

In [6]:
print (df.info())
print (df_test_eval.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814262 entries, 0 to 814261
Data columns (total 11 columns):
hash             814262 non-null object
trajectory_id    814262 non-null object
time_entry       814262 non-null object
time_exit        814262 non-null object
vmax             814262 non-null object
vmin             814262 non-null object
vmean            814262 non-null object
x_entry          814262 non-null float64
y_entry          814262 non-null float64
x_exit           814262 non-null float64
y_exit           814262 non-null float64
dtypes: float64(4), object(7)
memory usage: 68.3+ MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 169422 entries, 0 to 202935
Data columns (total 11 columns):
hash             169422 non-null object
trajectory_id    169422 non-null object
time_entry       169422 non-null timedelta64[ns]
time_exit        169422 non-null timedelta64[ns]
vmax             169422 non-null object
vmin             169422 non-null object
vmean            169422 non-null object
x_entry          169422 non-null float64
y_entry          169422 non-null float64
x_exit           169422 non-null object
y_exit           169422 non-null object
dtypes: float64(2), object(7), timedelta64[ns](2)
memory usage: 15.5+ MB
None

In [7]:
#Some statistics
df.describe()

            x_entry       y_entry        x_exit        y_exit
count  8.142620e+05  8.142620e+05  8.142620e+05  8.142620e+05
mean   3.760411e+06 -1.922153e+07  3.760426e+06 -1.922181e+07
std    8.974393e+03  7.632234e+04  8.904451e+03  7.515560e+04
min    3.741027e+06 -1.938291e+07  3.740998e+06 -1.937688e+07
25%    3.755174e+06 -1.927454e+07  3.755359e+06 -1.927308e+07
50%    3.760071e+06 -1.923020e+07  3.760076e+06 -1.923031e+07
75%    3.767509e+06 -1.916999e+07  3.767455e+06 -1.917193e+07
max    3.777099e+06 -1.904266e+07  3.777055e+06 -1.904666e+07

In [8]:
df.head()

,hash,trajectory_id,time_entry,time_exit,vmax,vmin,vmean,x_entry,y_entry,x_exit,y_exit
0,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_0,07:04:31,07:08:32,,,,3.751014e+06,-1.909398e+07,3.750326e+06,-1.913634e+07
1,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_1,07:20:34,07:25:42,,,,3.743937e+06,-1.932247e+07,3.744975e+06,-1.931966e+07
2,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_2,07:53:32,08:03:25,,,,3.744868e+06,-1.929356e+07,3.744816e+06,-1.929284e+07
3,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_3,08:17:50,08:37:23,,,,3.744880e+06,-1.929229e+07,3.744809e+06,-1.929049e+07
4,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_4,14:38:09,14:38:09,,,,3.744909e+06,-1.928558e+07,3.744909e+06,-1.928558e+07

In [12]:
#Prepare time stayed in the city hall (seconds)
df['time_entry_seconds'] = pd.to_timedelta(df['time_entry']).dt.total_seconds()
df['time_exit_seconds']=pd.to_timedelta(df['time_exit']).dt.total_seconds()
df['time_stayed_seconds']=df['time_exit_seconds']-df['time_entry_seconds']
df.head()

,hash,trajectory_id,time_entry,time_exit,vmax,vmin,vmean,x_entry,y_entry,x_exit,y_exit,time_entry_seconds,time_exit_seconds,time_stayed_seconds
0,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_0,07:04:31,07:08:32,,,,3.751014e+06,-1.909398e+07,3.750326e+06,-1.913634e+07,25471.0,25712.0,241.0
1,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_1,07:20:34,07:25:42,,,,3.743937e+06,-1.932247e+07,3.744975e+06,-1.931966e+07,26434.0,26742.0,308.0
2,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_2,07:53:32,08:03:25,,,,3.744868e+06,-1.929356e+07,3.744816e+06,-1.929284e+07,28412.0,29005.0,593.0
3,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_3,08:17:50,08:37:23,,,,3.744880e+06,-1.929229e+07,3.744809e+06,-1.929049e+07,29870.0,31043.0,1173.0
4,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_4,14:38:09,14:38:09,,,,3.744909e+06,-1.928558e+07,3.744909e+06,-1.928558e+07,52689.0,52689.0,0.0

In [16]:
#prepare whether entry point is in cityhall
df_target = df.loc[:,['x_entry','y_entry']]

target_x1 = df_target['x_entry']>=3750901.5068
target_x2 = df_target['x_entry']<=3770901.5068

target_x = target_x1 & target_x2

target_y1 = df_target['y_entry'] >= -19268905.6133
target_y2 = df_target['y_entry'] <= -19208905.6133

target_y = target_y1 & target_y2

df['entry_inside'] = 1*(target_x & target_y)

df.head()
df.entry_inside.describe()

count    814262.000000
mean          0.291157
std           0.454296
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: entry_inside, dtype: float64

In [17]:
#Prepare train data
df_train=df.loc[:,['time_stayed_seconds','entry_inside']]

train_data = df_train.values

train_data

array([[241.,   0.],
       [308.,   0.],
       [593.,   0.],
       ...,
       [  0.,   0.],
       [409.,   0.],
       [439.,   0.]])

In [18]:
#prepare training label
df_target = df.loc[:,['x_exit','y_exit']]

target_x1 = df_target['x_exit']>=3750901.5068
target_x2 = df_target['x_exit']<=3770901.5068

target_x = target_x1 & target_x2

target_y1 = df_target['y_exit'] >= -19268905.6133
target_y2 = df_target['y_exit'] <= -19208905.6133

target_y = target_y1 & target_y2

train_label = 1*(target_x & target_y)

print (train_label.describe())

train_label = train_label.values

train_label = to_categorical(train_label)

count    814262.000000
mean          0.298690
std           0.457684
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
dtype: float64

In [19]:
#Build model
model = Sequential()
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(2, activation='softmax'))

model.compile(optimizer='adagrad', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(train_data, train_label, epochs=1)

Epoch 1/1
814262/814262 [==============================] - 73s 90us/step - loss: 1.1854 - acc: 0.9038

In [21]:
#Preparing predicting data
df_test_pred['time_entry_seconds'] = pd.to_timedelta(df_test_pred['time_entry']).dt.total_seconds()
df_test_pred['time_exit_seconds']=pd.to_timedelta(df_test_pred['time_exit']).dt.total_seconds()
df_test_pred['time_stayed_seconds']=df_test_pred['time_exit_seconds']-df_test_pred['time_entry_seconds']


df_test_pred.head()

/Users/minseok/anaconda3/envs/py3.5_tf1.1/lib/python3.5/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/minseok/anaconda3/envs/py3.5_tf1.1/lib/python3.5/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/minseok/anaconda3/envs/py3.5_tf1.1/lib/python3.5/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,hash,trajectory_id,time_entry,time_exit,vmax,vmin,vmean,x_entry,y_entry,x_exit,y_exit,time_entry_seconds,time_exit_seconds,time_stayed_seconds
4,00032f51796fd5437b238e3a9823d13d_31,traj_00032f51796fd5437b238e3a9823d13d_31_5,15:03:32,15:10:32,,,,3.773118e+06,-1.914490e+07,,,54212.0,54632.0,420.0
7,000479418b5561ab694a2870cc04fd43_25,traj_000479418b5561ab694a2870cc04fd43_25_10,15:29:09,15:30:56,,,,3.769978e+06,-1.934136e+07,,,55749.0,55856.0,107.0
10,000506a39775e5bca661ac80e3f466eb_29,traj_000506a39775e5bca661ac80e3f466eb_29_5,15:26:08,15:26:08,,,,3.757468e+06,-1.923860e+07,,,55568.0,55568.0,0.0
13,0005401ceddaf27a9b7f0d42ef1fbe95_1,traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4,15:35:18,15:42:05,,,,3.760505e+06,-1.935500e+07,,,56118.0,56525.0,407.0
17,00063a4f6c12e1e4de7d876580620667_3,traj_00063a4f6c12e1e4de7d876580620667_3_4,14:54:07,15:05:14,,,,3.766319e+06,-1.917013e+07,,,53647.0,54314.0,667.0

In [22]:
#prepare predicting data
df_target = df_test_pred.loc[:,['x_entry','y_entry']]

target_x1 = df_target['x_entry']>=3750901.5068
target_x2 = df_target['x_entry']<=3770901.5068

target_x = target_x1 & target_x2

target_y1 = df_target['y_entry'] >= -19268905.6133
target_y2 = df_target['y_entry'] <= -19208905.6133

target_y = target_y1 & target_y2

df_test_pred['entry_inside'] = 1*(target_x & target_y)

df_test_pred.head()
df_test_pred.entry_inside.describe()

/Users/minseok/anaconda3/envs/py3.5_tf1.1/lib/python3.5/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

count    33515.000000
mean         0.284768
std          0.451311
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000
Name: entry_inside, dtype: float64

In [23]:
#prepare test_data_pred
test_data_pred = df_test_pred.loc[:,['time_stayed_seconds','entry_inside']]
test_data_pred = test_data_pred.values

test_data_pred

array([[420.,   0.],
       [107.,   0.],
       [  0.,   1.],
       ...,
       [  0.,   0.],
       [331.,   0.],
       [  0.,   0.]])

In [27]:
#Make predictions
predictions = model.predict(test_data_pred)

predictions = (predictions[:,1]>0.5)*1

print (predictions)

[0 0 1 ... 0 0 0]

In [28]:
#Save
id = pd.DataFrame(df_test_pred['trajectory_id'])

target = pd.DataFrame(predictions)
target.columns = ['target']


output = pd.concat([id.reset_index(drop=True),target.reset_index(drop=True)], axis=1)
output.columns = ['id', 'target']
output.to_csv("try_2.csv", index=False)

In [32]:
#debugging
print("test_data_pred", test_data_pred.shape)
print("predictions", predictions.shape)
print("df_test_pred", df_test_pred.shape)
print("id", id.shape)
print("target", target.shape)
print("output", output.shape)

print (target.describe())

print(output)

test_data_pred (33515, 2)
predictions (33515,)
df_test_pred (33515, 15)
id (33515, 1)
target (33515, 1)
output (33515, 2)
             target
count  33515.000000
mean       0.258571
std        0.437856
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000
                                                id  target
0       traj_00032f51796fd5437b238e3a9823d13d_31_5       0
1      traj_000479418b5561ab694a2870cc04fd43_25_10       0
2       traj_000506a39775e5bca661ac80e3f466eb_29_5       1
3        traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4       0
4        traj_00063a4f6c12e1e4de7d876580620667_3_4       0
5       traj_0006535be25bb52dd06983447880c964_5_12       0
6       traj_0006f84bb33ec929d1cda7686f861d0a_31_3       1
7      traj_00093ae562586aed0e053b8431e8ace4_23_10       0
8       traj_000c739e444a70e1804d757a0580caaa_31_3       1
9       traj_000d479078af08618bddc7f09082b8c3_11_6       0
10     traj_000d6fba12a7d06defe90e3c9162c11e_29_11       1
11      traj_000efd6f95db39d6ba35027f02b5628f_9_20       0
12     traj_000feace3a33be9245e2783cdff467a8_15_12       0
13       traj_0011b48d0cf4f962833edd701afaf419_3_7       0
14      traj_001484cf0f956c316070be4b4c6352ff_29_7       0
15       traj_001d29060cfe35996cfeb141210ecbeb_9_2       1
16       traj_001dff40eab7eea1c10d0fadcea0c779_9_7       0
17      traj_001f9345a2979c553125c65499630f25_29_3       0
18      traj_002447d99e8f6c3bc6c1329140979a91_25_7       0
19      traj_002531dea45cd4059e92099630ebf775_3_10       0
20      traj_00265578639bd4d35a3524a1463d98bb_31_8       0
21      traj_0026d48a63f219dc359f1131805909bf_31_5       0
22      traj_002f7d1d09d2af27ee5a6d0fa4e91c96_29_8       1
23      traj_0032262ce8e9e5e3750f306a2ace8d4a_25_4       1
24      traj_0033b16d18ce91c89eafacb1cb3a5a44_11_4       0
25     traj_00351550555ffcb00b52d21bcaabfadf_31_11       0
26     traj_003539963b1eebf6088d3d5302e45232_31_12       0
27      traj_00390d9128b5d9c7ba1b32c8babb6c24_11_2       0
28       traj_003a9e30d316e8fc524ac36f9deac690_1_5       0
29       traj_003d9b2742ddcd1a37717c524135b3d4_3_2       0
...                                            ...     ...
33485    traj_ffb5f2a2b26610380802fdcd9bad632c_1_3       1
33486   traj_ffb6f598b7194db26036098ac007acc2_19_9       0
33487    traj_ffb710d354ecbe6163aa2ee5e0883447_9_9       0
33488   traj_ffb78d018356f592ae576c9628a45484_25_6       0
33489    traj_ffb9db79c6b96d152334efa2c1d06fab_3_7       0
33490  traj_ffbc7807308dedf49523080af5d79eed_29_15       1
33491   traj_ffbf4376c763fac389a8846072d07799_23_2       0
33492   traj_ffc4a4d656ea7e6bce1775aa23d48d48_31_7       0
33493   traj_ffc4e987fb10a9a768a98c464540bcb3_23_2       0
33494   traj_ffc880cc98b30c6905a1bac96153de0c_23_7       0
33495   traj_ffca386c11dbd2007a3e58ccb6a782e0_15_5       0
33496   traj_ffcb11743cc9dc1129fdfb207ca5375b_15_3       0
33497    traj_ffcdb92dfa0b6771787205ff32a43d7d_1_8       0
33498   traj_ffce1404987f65b6807f600e9c786ac8_5_15       0
33499    traj_ffd18e6378c5384cfb135c569e0ef8f2_9_4       1
33500   traj_ffd395ec3142de6fa43c6c4c8196191c_11_8       0
33501  traj_ffd3d9d488e22ac1558536d56cef0c1b_23_13       0
33502  traj_ffd6099333016778d39013a2e5f4c0e3_29_11       1
33503    traj_ffd9243bfaa2802879e77b08c3c99c81_9_8       0
33504   traj_ffd97ad509d7b0c17b40d93cfb8def44_31_3       0
33505    traj_ffe12e09e01554bc5bcc2661290c11d9_3_3       1
33506   traj_ffe474fc44b2a5c0b5f733c51d27ab35_31_2       0
33507  traj_ffe4cfa385932e1db09e85d8bd73609d_11_10       0
33508   traj_ffe54b47c077d8c5c27dd608ffac09d1_9_11       0
33509    traj_ffe7b16199fab37e6c1f4eae7d2e5d64_1_3       0
33510  traj_ffe98f6e0adf12f9c7b51c4e9607a87a_15_13       0
33511   traj_fff607ecd3f8d3dcb65791e8b4c22a5f_3_25       1
33512   traj_fff813b56230c2f026f783f5b9f9ca90_19_0       0
33513  traj_fff9400843a88c3bfe52e7ce8bf97316_19_17       0
33514   traj_fff9552047b095e8242b4913f3289a26_25_7       0

[33515 rows x 2 columns]